{{ if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4}}
type: Opaque
data:
  DATABASE_WH_PASS: {{ .Values.database.wh.password | default .Values.global.semanticGrid.database.wh.password | b64enc }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | b64enc }}
  ANTHROPIC_API_KEY: {{ .Values.anthropicApiKey | b64enc }}
  DEEPSEEK_AI_API_KEY: {{ .Values.deepSeekApiKey | b64enc }}
{{- with .Values.database.internal.password }}
  DATABASE_PASS: {{ . | b64enc }}
{{- end }}
{{- with .Values.rabbitmqExternalConnection }}
  WRK_BROKER_CONNECTION: {{ . | b64enc }}
{{- end }}
{{ end -}}
