import type { Dashboard, DashboardItem, Query } from "@/app/lib/dashboards";

export const dashboards: Dashboard[] = [
  {
    id: "1",
    name: "Home",
    slug: "/",
    description: "Solana DEX Activity At a Glance",
  },
  {
    id: "2",
    name: "Tokens",
    slug: "/tokens",
    description: "Most Performing Tokens and Market Trends",
  },
  {
    id: "3",
    name: "Trends",
    slug: "/trends",
    description: "What's Hot On The Market Today",
  },
  {
    id: "4",
    name: "Traders",
    slug: "/traders",
    description: "Wallets Making Waves and Profit",
  },
  {
    id: "99999",
    name: "User",
    slug: "/user",
    description: "Your Personal Solana Dashboard",
  },
];

export const queries: Query[] = [
  {
    id: "q1",
    queryUid: "8ee0c689-3853-4052-9e9f-a52fde8c881d",
    description: "WSOL Trading Volume For the Past 7 Days",
  },
  {
    id: "q2",
    // queryId: "a6bf97ff-4d8c-48f2-9c2a-ecf90e06dcf5",
    queryUid: "82603d68-9f16-4752-a5b0-84c9bd079a34",
    description: "Top 20 Trading Tokens, 24H",
  },
  {
    id: "q21",
    queryUid: "a6bf97ff-4d8c-48f2-9c2a-ecf90e06dcf5",
    // queryId: "82603d68-9f16-4752-a5b0-84c9bd079a34",
    description: "Top 20 Trading Tokens, 7D",
  },
  {
    id: "q3",
    queryUid: "0184da22-0dab-4aee-843c-01aaf035c891",
    description: "DEX Trades For The Past 7 Days",
  },
  {
    id: "q4",
    queryUid: "388a053f-aedf-44da-83dc-c99d0c24ba19",
    description: "Top 10 Traders For the Past 24h",
  },
  {
    id: "q5",
    queryUid: "91406c57-6fb1-4025-8a92-5d51af6e3f65",
    description: "Tokens traded for last 7 days",
  },
  {
    id: "q6",
    queryUid: "0fca1837-2685-4e27-a0d1-e822350c842a",
    description: "WSOL buys and sells for last 7 days",
  },
  {
    id: "q7",
    queryUid: "642dfc7b-b1dc-407c-90ef-cf5104e40f6b",
    description: "High-Traded Tokens For the Past 7 Days",
  },
  {
    id: "q71",
    queryUid: "432af35d-06e8-4a45-87be-9d593af923c7",
    description: "High-Traded Tokens For the Past 24H",
  },
  {
    id: "q8",
    queryUid: "dc2c9190-530f-40e1-8c0c-7637e2c85e69",
    description: "DEX Volumes For the Past 7 Days",
  },
  {
    id: "q9",
    queryUid: "fb497a12-5679-46e4-a5f7-99ae49c63e68",
    description: "TX Count, 7 Days",
  },
  {
    id: "q10",
    queryUid: "10bf2379-6d58-4e1a-8fcc-6dcb45b33fd0",
    description: "Top 10 USDC Spenders, 24H",
  },
  {
    id: "q11",
    queryUid: "71e7457d-7d59-4834-b34e-89e2d765814d",
    description: "5m DEX pair stats, 2H",
  },
];

export const dashboardItems: DashboardItem[] = [
  {
    id: "d0",
    dashboardId: "1",
    queryId: "q9",
    description: "TX Count, 7 Days",
    name: "TX Count, 7 Days",
    itemType: "chart",
    chartType: "line",
  },
  {
    id: "di1-1",
    dashboardId: "1",
    queryId: "q1",
    description: "WSOL Trading Volume For the Past 7 Days",
    name: "WSOL Trading Volume For the Past 7 Days",
    itemType: "chart",
    chartType: "line",
  },
  {
    id: "di1-2",
    dashboardId: "1",
    queryId: "q6",
    description: "WSOL buys and sells for last 7 days",
    name: "WSOL buys and sells for last 7 days",
    itemType: "chart",
    chartType: "line",
  },
  {
    id: "di1-3",
    dashboardId: "1",
    queryId: "q7",
    description: "High-Traded Tokens, 7D",
    name: "High-Traded Tokens, 7D",
    itemType: "chart",
    chartType: "line",
  },
  {
    id: "di2",
    dashboardId: "2",
    queryId: "q2",
    name: "Top 20 Traded Tokens, 24H",
    description: "Top 20 Traded Tokens, 24H",
    itemType: "table",
  },
  {
    id: "di21",
    dashboardId: "2",
    queryId: "q21",
    name: "Top 20 Traded Tokens, 7D",
    description: "Top 20 Traded Tokens, 7D",
    itemType: "table",
  },
  {
    id: "di2-2",
    dashboardId: "1",
    queryId: "q71",
    name: "High Traded Tokens, 24H",
    description: "High Traded Tokens, 24H",
    itemType: "chart",
    chartType: "line",
  },
  {
    id: "di2-1",
    dashboardId: "2",
    queryId: "q2",
    name: "Top 20 Traded Tokens",
    description: "Top 20 Traded Tokens",
    itemType: "chart",
    chartType: "pie",
  },
  {
    id: "di3",
    dashboardId: "1",
    queryId: "q3",
    name: "DEX Trades For The Past 7 Days",
    description: "DEX Trades For The Past 7 Days",
    itemType: "chart",
    chartType: "line",
  },
  {
    id: "di9",
    dashboardId: "1",
    queryId: "q8",
    description: "DEX Volumes For the Past 7 Days",
    name: "DEX Volumes For the Past 7 Days",
    itemType: "chart",
    chartType: "line",
  },
  {
    id: "di4",
    dashboardId: "4",
    queryId: "q4",
    name: "Top 10 Traders For the Past 24h",
    description: "Top 10 Traders For the Past 24h",
    itemType: "chart",
    chartType: "pie",
  },
  {
    id: "di5",
    dashboardId: "3",
    queryId: "q5",
    name: "Tokens traded for last 7 days",
    description: "Tokens traded for last 7 days",
    itemType: "chart",
    chartType: "line",
  },
  {
    id: "di6",
    dashboardId: "4",
    queryId: "q10",
    description: "Top 10 USDC Spenders, 24H",
    name: "Top 10 USDC Spenders, 24H",
    itemType: "chart",
    chartType: "pie",
  },
  {
    id: "di7",
    dashboardId: "3",
    queryId: "q11",
    description: "5m DEX pair stats (2h)",
    name: "5m DEX pair stats (2h)",
    itemType: "chart",
    chartType: "line",
  },
];
