apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4}}
data:
  APEGPT_API_URL: "{{ include "fm-app.url" . }}"
{{- with .Values.auth0 }}
  AUTH0_ISSUER_BASE_URL: "{{ .issuerBaseUrl }}"
  AUTH0_CLIENT_ID: "{{ .clientId }}"
  AUTH0_AUDIENCE: "{{ .audience }}"
  AUTH0_BASE_URL: "{{ .baseUrl }}"
{{- end }}
  JWT_PRIVATE_KEY: "/run/secrets/{{ include "common.names.fullname" . }}/guest-web-jwt-secret-id-rsa"
  JWT_PUBLIC_KEY: "/run/secrets/{{ include "common.names.fullname" . }}/guest-web-jwt-secret-id-rsa.pub"
{{- with .Values.guestAuth }}
  GUEST_AUTH_ISSUER: "{{ .issuer }}"
{{- end }}
{{- with .Values.freeTierQuota }}
  FREE_TIER_QUOTA: {{ .Values.freeTierQuota | quote }}
{{- end }}

