{{ if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4}}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "" # FIXME: do we neet it?
  AWS_SECRET_ACCESS_KEY: "" # FIXME: do we neet it?
  AUTH0_CLIENT_SECRET: {{ .Values.auth0.clientSecret | b64enc | quote }}
  AUTH0_SECRET:  {{ .Values.auth0.secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-files
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4}}
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
{{ end -}}
