###Expired token
POST http://127.0.0.1:8000/api/v1/session
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InFPZTJKaUhRQmtYRU5wal9PcFNoUiJ9.eyJpc3MiOiJodHRwczovL2FwZS1ncHQtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDk0MjcxNzc4NTI1NDk2ODc1NSIsImF1ZCI6WyJodHRwOi8vYXBlLWdwdC1hcGktZGV2IiwiaHR0cHM6Ly9hcGUtZ3B0LWRldi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzMxMDE1NDgzLCJleHAiOjE3MzExMDE4ODMsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeCIsInBlcm1pc3Npb25zIjpbXX0.nWo2jY0iTfnLmR6o0powo1CB4B7E1X_c3n8W3FJmH257JAoSMLMptS5Ctw8vHaue9eb3xnr6zTUffNRiDRnc1CWuL9-JEShIgb1KIRtnhLx7Pc8xRyM4-W-en7iyzjrzAAuGSEWUAsjvvG6TwF9PPgEKibY8ARWaFRizEteaFzworw5FREWfvLzsfzif1RbX6Dc5tpXkojKE2fxZJo0b1U03VB7ofwzc7MVDEUYIzb6woos8bEmEqobCH_MIOndu5JVwDh7j5GXzuhM_wL2vzsHRcR9oXC3Wdo-fBLspOtgU9WA6M7lRKZNW5D26_rRJRwAhdIwpSd4ALzzmW6rkGw

{
}

###Create session
POST http://127.0.0.1:8000/api/v1/session
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InFPZTJKaUhRQmtYRU5wal9PcFNoUiJ9.eyJpc3MiOiJodHRwczovL2FwZS1ncHQtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2FwZS1ncHQtYXBpLWRldiIsImlhdCI6MTczMTEwMzE1NiwiZXhwIjoxNzMxMTg5NTU2LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeCIsInBlcm1pc3Npb25zIjpbXX0.S1h7focnM7Q2vYfhe6cS0fcqcMBNsH2Ga9LLrZKkKD22HL2J3MdtfMKsx1UfMA1qz6kgqqGXVk0Vei4l8cF91n4v1TK2s53YJZSj22aBIiqPuxZlAW7xzy52ugv9M5vxFBcK6_YbscV_fXV60JSd1c5X_h0IXU7k5fxTGXTX9wRWQfl9dZPpWhfpWeexZsX1zQGXuWQolygQC9fCBU2uFlb93t0iCtgC7WmgPRA1yjZCCgKe7PVLXZmeBdErgqQ0BnoFtPPPpUZ9kvJBk_ukJ5LfGV0Y99n0CJOVyr6wtOLkF9e-ibFsJLX23CzhHPOU8t5A9qKARBxtoNdNiIZ8Iw

{
}

###Get all sessions
GET http://127.0.0.1:8000/api/v1/session
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InFPZTJKaUhRQmtYRU5wal9PcFNoUiJ9.eyJpc3MiOiJodHRwczovL2FwZS1ncHQtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2FwZS1ncHQtYXBpLWRldiIsImlhdCI6MTczMTEwMzE1NiwiZXhwIjoxNzMxMTg5NTU2LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeCIsInBlcm1pc3Npb25zIjpbXX0.S1h7focnM7Q2vYfhe6cS0fcqcMBNsH2Ga9LLrZKkKD22HL2J3MdtfMKsx1UfMA1qz6kgqqGXVk0Vei4l8cF91n4v1TK2s53YJZSj22aBIiqPuxZlAW7xzy52ugv9M5vxFBcK6_YbscV_fXV60JSd1c5X_h0IXU7k5fxTGXTX9wRWQfl9dZPpWhfpWeexZsX1zQGXuWQolygQC9fCBU2uFlb93t0iCtgC7WmgPRA1yjZCCgKe7PVLXZmeBdErgqQ0BnoFtPPPpUZ9kvJBk_ukJ5LfGV0Y99n0CJOVyr6wtOLkF9e-ibFsJLX23CzhHPOU8t5A9qKARBxtoNdNiIZ8Iw

###Patch sessions
PATCH http://127.0.0.1:8000/api/v1/session/0672eb33-5a08-742f-8000-fe94eed83713
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InFPZTJKaUhRQmtYRU5wal9PcFNoUiJ9.eyJpc3MiOiJodHRwczovL2FwZS1ncHQtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2FwZS1ncHQtYXBpLWRldiIsImlhdCI6MTczMTEwMzE1NiwiZXhwIjoxNzMxMTg5NTU2LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeCIsInBlcm1pc3Npb25zIjpbXX0.S1h7focnM7Q2vYfhe6cS0fcqcMBNsH2Ga9LLrZKkKD22HL2J3MdtfMKsx1UfMA1qz6kgqqGXVk0Vei4l8cF91n4v1TK2s53YJZSj22aBIiqPuxZlAW7xzy52ugv9M5vxFBcK6_YbscV_fXV60JSd1c5X_h0IXU7k5fxTGXTX9wRWQfl9dZPpWhfpWeexZsX1zQGXuWQolygQC9fCBU2uFlb93t0iCtgC7WmgPRA1yjZCCgKe7PVLXZmeBdErgqQ0BnoFtPPPpUZ9kvJBk_ukJ5LfGV0Y99n0CJOVyr6wtOLkF9e-ibFsJLX23CzhHPOU8t5A9qKARBxtoNdNiIZ8Iw

 {
    "name": "name_new2",
    "tags": "new_tags2"
  }

###Add request
POST http://127.0.0.1:8000/api/v1/request/0672eb33-5a08-742f-8000-fe94eed83713
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InFPZTJKaUhRQmtYRU5wal9PcFNoUiJ9.eyJpc3MiOiJodHRwczovL2FwZS1ncHQtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2FwZS1ncHQtYXBpLWRldiIsImlhdCI6MTczMTEwMzE1NiwiZXhwIjoxNzMxMTg5NTU2LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeCIsInBlcm1pc3Npb25zIjpbXX0.S1h7focnM7Q2vYfhe6cS0fcqcMBNsH2Ga9LLrZKkKD22HL2J3MdtfMKsx1UfMA1qz6kgqqGXVk0Vei4l8cF91n4v1TK2s53YJZSj22aBIiqPuxZlAW7xzy52ugv9M5vxFBcK6_YbscV_fXV60JSd1c5X_h0IXU7k5fxTGXTX9wRWQfl9dZPpWhfpWeexZsX1zQGXuWQolygQC9fCBU2uFlb93t0iCtgC7WmgPRA1yjZCCgKe7PVLXZmeBdErgqQ0BnoFtPPPpUZ9kvJBk_ukJ5LfGV0Y99n0CJOVyr6wtOLkF9e-ibFsJLX23CzhHPOU8t5A9qKARBxtoNdNiIZ8Iw

 {
"request": "this is test request"
 }

###Get one request
GET http://127.0.0.1:8000/api/v1/request/0672eb33-5a08-742f-8000-fe94eed83713/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InFPZTJKaUhRQmtYRU5wal9PcFNoUiJ9.eyJpc3MiOiJodHRwczovL2FwZS1ncHQtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2FwZS1ncHQtYXBpLWRldiIsImlhdCI6MTczMTEwMzE1NiwiZXhwIjoxNzMxMTg5NTU2LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeCIsInBlcm1pc3Npb25zIjpbXX0.S1h7focnM7Q2vYfhe6cS0fcqcMBNsH2Ga9LLrZKkKD22HL2J3MdtfMKsx1UfMA1qz6kgqqGXVk0Vei4l8cF91n4v1TK2s53YJZSj22aBIiqPuxZlAW7xzy52ugv9M5vxFBcK6_YbscV_fXV60JSd1c5X_h0IXU7k5fxTGXTX9wRWQfl9dZPpWhfpWeexZsX1zQGXuWQolygQC9fCBU2uFlb93t0iCtgC7WmgPRA1yjZCCgKe7PVLXZmeBdErgqQ0BnoFtPPPpUZ9kvJBk_ukJ5LfGV0Y99n0CJOVyr6wtOLkF9e-ibFsJLX23CzhHPOU8t5A9qKARBxtoNdNiIZ8Iw

###Get all request
GET http://127.0.0.1:8000/api/v1/session/get_requests/0672eb33-5a08-742f-8000-fe94eed83713
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InFPZTJKaUhRQmtYRU5wal9PcFNoUiJ9.eyJpc3MiOiJodHRwczovL2FwZS1ncHQtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2FwZS1ncHQtYXBpLWRldiIsImlhdCI6MTczMTEwMzE1NiwiZXhwIjoxNzMxMTg5NTU2LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJ4YjVCQWhHMjdsUDRueW5xaVQ3bVBBV1JEblZOMzJxeCIsInBlcm1pc3Npb25zIjpbXX0.S1h7focnM7Q2vYfhe6cS0fcqcMBNsH2Ga9LLrZKkKD22HL2J3MdtfMKsx1UfMA1qz6kgqqGXVk0Vei4l8cF91n4v1TK2s53YJZSj22aBIiqPuxZlAW7xzy52ugv9M5vxFBcK6_YbscV_fXV60JSd1c5X_h0IXU7k5fxTGXTX9wRWQfl9dZPpWhfpWeexZsX1zQGXuWQolygQC9fCBU2uFlb93t0iCtgC7WmgPRA1yjZCCgKe7PVLXZmeBdErgqQ0BnoFtPPPpUZ9kvJBk_ukJ5LfGV0Y99n0CJOVyr6wtOLkF9e-ibFsJLX23CzhHPOU8t5A9qKARBxtoNdNiIZ8Iw
