{{ if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
type: Opaque
data:
  DATABASE_WH_PASS: {{ .Values.database.wh.password | default .Values.global.semanticGrid.database.wh.password | b64enc }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | b64enc }}
{{ end -}}
